# Generated by Django 2.2.6 on 2019-11-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('marital', models.TextField()),
                ('retire', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_and_bonus', models.IntegerField()),
                ('sal_ends', models.PositiveSmallIntegerField()),
                ('exp_sal_growth_in_per', models.PositiveSmallIntegerField()),
                ('rent', models.IntegerField()),
                ('rent_ends', models.PositiveSmallIntegerField()),
                ('exp_growth', models.PositiveSmallIntegerField()),
                ('business', models.IntegerField()),
                ('business_ends', models.PositiveSmallIntegerField()),
                ('business_growth', models.PositiveSmallIntegerField()),
                ('other', models.IntegerField()),
                ('other_ends', models.PositiveSmallIntegerField()),
                ('other_growth', models.PositiveSmallIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualfunds.users')),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.IntegerField()),
                ('regular_ends', models.PositiveSmallIntegerField()),
                ('exp_inf_reg', models.PositiveSmallIntegerField()),
                ('uti', models.IntegerField()),
                ('uti_ends', models.PositiveSmallIntegerField()),
                ('exp_inf_uti', models.PositiveSmallIntegerField()),
                ('grocery', models.IntegerField()),
                ('grocery_ends', models.PositiveSmallIntegerField()),
                ('exp_inf_groc', models.PositiveSmallIntegerField()),
                ('mon_leisure', models.IntegerField()),
                ('leisure_ends', models.PositiveSmallIntegerField()),
                ('me', models.IntegerField()),
                ('me_ends', models.PositiveSmallIntegerField()),
                ('me_inf', models.PositiveSmallIntegerField()),
                ('ds', models.IntegerField()),
                ('ds_ends', models.PositiveSmallIntegerField()),
                ('exp_les_inf', models.PositiveSmallIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutualfunds.users')),
            ],
        ),
    ]
