# Generated by Django 2.2.6 on 2019-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='exp_ds_inf',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
