# Generated by Django 2.2.6 on 2019-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='marital',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='retire',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
