# Generated by Django 2.2.6 on 2019-11-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0002_expenses_exp_ds_inf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='email',
        ),
    ]
