# Generated by Django 2.2.6 on 2019-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0003_users_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_and_bonus', models.IntegerField()),
                ('sal_ends', models.PositiveSmallIntegerField()),
                ('exp_sal_growth_in_per', models.PositiveSmallIntegerField()),
                ('rent', models.IntegerField()),
                ('rent_ends', models.PositiveSmallIntegerField()),
                ('exp_growth', models.PositiveSmallIntegerField()),
                ('business', models.IntegerField()),
                ('business_ends', models.PositiveSmallIntegerField()),
                ('business_growth', models.PositiveSmallIntegerField()),
                ('other', models.IntegerField()),
                ('other_ends', models.PositiveSmallIntegerField()),
                ('other_growth', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.TextField(default='2019-11-02 21:12:49.059718'),
        ),
    ]
