# Generated by Django 2.2.6 on 2019-11-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0003_remove_expenses_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='expenses',
        ),
    ]
