# Generated by Django 2.2.6 on 2019-11-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0004_auto_20191102_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
    ]
