# Generated by Django 2.2.6 on 2019-11-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0005_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='email',
        ),
        migrations.AddField(
            model_name='expenses',
            name='emi1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='emi1_end',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='emi2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='emi2_end',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
