# Generated by Django 2.2.6 on 2019-11-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0006_auto_20191103_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqshare', models.IntegerField()),
                ('mutual', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='expenses',
        ),
    ]
