# Generated by Django 2.2.6 on 2019-11-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.IntegerField()),
                ('regular_ends', models.PositiveSmallIntegerField()),
                ('exp_inf_reg', models.PositiveSmallIntegerField()),
                ('uti', models.IntegerField()),
                ('uti_ends', models.PositiveSmallIntegerField()),
                ('exp_inf_uti', models.PositiveSmallIntegerField()),
                ('grocery', models.IntegerField()),
                ('grocery_ends', models.PositiveSmallIntegerField()),
                ('exp_inf_groc', models.PositiveSmallIntegerField()),
                ('mon_leisure', models.IntegerField()),
                ('leisure_ends', models.PositiveSmallIntegerField()),
                ('exp_les_inf', models.PositiveSmallIntegerField()),
                ('me', models.IntegerField()),
                ('me_ends', models.PositiveSmallIntegerField()),
                ('me_inf', models.PositiveSmallIntegerField()),
                ('ds', models.IntegerField()),
                ('ds_ends', models.PositiveSmallIntegerField()),
                ('exp_ds_inf', models.PositiveSmallIntegerField()),
                ('emi1', models.IntegerField()),
                ('emi1_end', models.PositiveSmallIntegerField()),
                ('emi2', models.IntegerField()),
                ('emi2_end', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
