from django.db import models
# Create your models here.
class users(models.Model):
    name = models.TextField()
    age = models.PositiveSmallIntegerField()
    email = models.EmailField(max_length=254)
    contact = models.BigIntegerField()
    marital = models.TextField()
    retire = models.PositiveSmallIntegerField()

class income(models.Model):
    email = models.ForeignKey(users, on_delete=models.CASCADE)
    sal_and_bonus = models.IntegerField()
    sal_ends = models.PositiveSmallIntegerField()
    exp_sal_growth_in_per = models.PositiveSmallIntegerField()
    rent = models.IntegerField()
    rent_ends = models.PositiveSmallIntegerField()
    exp_growth = models.PositiveSmallIntegerField()
    business=models.IntegerField()
    business_ends=models.PositiveSmallIntegerField()
    business_growth=models.PositiveSmallIntegerField()
    other = models.IntegerField()
    other_ends=models.PositiveSmallIntegerField()
    other_growth = models.PositiveSmallIntegerField()

class expenses(models.Model):
    regular = models.IntegerField()
    regular_ends = models.PositiveSmallIntegerField()
    exp_inf_reg = models.PositiveSmallIntegerField()
    uti = models.IntegerField()
    uti_ends = models.PositiveSmallIntegerField()
    exp_inf_uti = models.PositiveSmallIntegerField()
    grocery=models.IntegerField()
    grocery_ends=models.PositiveSmallIntegerField()
    exp_inf_groc=models.PositiveSmallIntegerField()
    mon_leisure = models.IntegerField()
    leisure_ends=models.PositiveSmallIntegerField()
    exp_les_inf = models.PositiveSmallIntegerField()
    me = models.IntegerField()
    me_ends=models.PositiveSmallIntegerField()
    me_inf = models.PositiveSmallIntegerField()
    ds = models.IntegerField()
    ds_ends=models.PositiveSmallIntegerField()
    exp_ds_inf = models.PositiveSmallIntegerField()
    emi1 = models.IntegerField()
    emi1_end = model.PositiveSmallIntegerField()
    emi2 = models.IntegerField()
    emi2_end = models.PositiveSmallIntegerField()

class portfolio(models.Model):
    equity = models.IntegerField()
    mutual = models.IntegerField()

class goals(models.Model):
    g1_start = models.PositiveSmallIntegerField()
    g1 = models.IntegerField()
    g1_inf = models.PositiveSmallIntegerField()
    g2_start = models.PositiveSmallIntegerField()
    g2 = models.IntegerField()
    g2_inf = models.PositiveSmallIntegerField()
    g3_start = models.PositiveSmallIntegerField()
    g3 = models.IntegerField()
    g3_inf = models.PositiveSmallIntegerField()
    g4_start = models.PositiveSmallIntegerField()
    g4 = models.IntegerField()
    g4_inf = models.PositiveSmallIntegerField()
    g5_start = models.PositiveSmallIntegerField()
    g5_cost = models.IntegerField()
    g5_inf = models.PositiveSmallIntegerField()

class freq_goals(models.Model):
    freq1 = models.IntegerField()
    freq1_start = models.PositiveSmallIntegerField()
    freq1_end = models.PositiveSmallIntegerField()
    freq1_freq = models.PositiveSmallIntegerField()
    freq1_inf = models.PositiveSmallIntegerField()
    freq2 = models.IntegerField()
    freq2_start = models.PositiveSmallIntegerField()
    freq2_end = models.PositiveSmallIntegerField()
    freq2_freq = models.PositiveSmallIntegerField()
    freq2_inf = models.PositiveSmallIntegerField()
